### ISSUE TITLE
Method 'BlockUpdate' in type 'MimeKit.Cryptography.Ed25519DigestSigner'does not have an implementation.

### ISSUE THREAD

**Issue by jvorwerk** [jstedfast/MimeKit#1121]
**Describe the bug**

When trying to sign a message with DKIM Signer, I got the following error:

Method 'BlockUpdate' in type 'MimeKit.Cryptography.Ed25519DigestSigner' from assembly 'MimeKit, Version=4.9.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' does not have an implementation.

**Platform (please complete the following information):**
 - OS: [Linux, MacOS]
 - .NET Runtime: [e.g. CoreC]
 - .NET Framework: [e.g. .Net 6]
 - MimeKit Version: 4.9.0

**To Reproduce**
**Expected behavior**
I expect that the message will be signed

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
DkimSigner lSigner = new DkimSigner(MTA_Helper.Settings.DKim_PathToPrivateKey, MTA_Helper.Settings.DKim_Domain, MTA_Helper.Settings.DKim_Selector)
  {
      HeaderCanonicalizationAlgorithm = DkimCanonicalizationAlgorithm.Simple,
      BodyCanonicalizationAlgorithm = DkimCanonicalizationAlgorithm.Simple,
      AgentOrUserIdentifier = "@" + MTA_Helper.Settings.DKim_Domain,
      QueryMethod = "dns/txt",
  };
 
  //Sign the message
  List<string> lHeaderList =
      ["From", "Subject", "To", "List-Unsubscribe", "List-Unsubscribe-Post", "X-CSA-Complaints"];
  lSigner.Sign(aMimeMessage, lHeaderList);
```

**Additional context**
It used to work in older versions

**Comment by jstedfast** [comment]
Can you paste the full stack trace?

**Comment by jvorwerk** [comment]
Here it is:

   at MimeKit.Cryptography.DkimSignerBase.CreateSigningContext()
   at MimeKit.Cryptography.DkimSigner.DkimSign(FormatOptions options, MimeMessage message, IList`1 headers)
   at MimeKit.Cryptography.DkimSigner.Sign(FormatOptions options, MimeMessage message, IList`1 headers)
   at MimeKit.Cryptography.DkimSigner.Sign(MimeMessage message, IList`1 headers)
   at MNR_Worker_MTA.Classes.MTA_SendMail.SignMessage_Provider(MimeMessage& aMimeMessage)

**Comment by jstedfast** [comment]
Okay, so the problem is that you are actually using the netstandard2.1 version of MimeKit starting with MimeKit 4.9.0 because I dropped net6.0 support (following Microsoft's lead).

BouncyCastle, which provides the ISigner and Idigest interfaces, exposes `BlockUpdate(ReadOnlySpan<byte>)` for NetCoreApp >= 2.1 and NetStandard >= 2.1, but MimeKit only provides those implementations for NetCore >= 6.0

I tried using the same #if-def's as BouncyCastle, but it won't compile because VS/Roslyn/Compiler insists that that API is only available for net6.0 and net8.0 (I still build for net6.0 locally due to CI build bots lagging behind).

**Comment by jstedfast** [comment]
* IDigest API: https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/IDigest.cs
* ISigner API: https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/ISigner.cs

**Comment by jstedfast** [comment]
And it looks like BouncyCastle only builds for the following frameworks:

```xml
<TargetFrameworks>net6.0;netstandard2.0;net461</TargetFrameworks>
```

Which explains why I can't seem to expose that API for netstandard2.1 (because there is no netstandard2.1 assembly of BouncyCastle).

**Comment by jstedfast** [comment]
What is happening is that you are essentially hitting this bug: https://github.com/bcgit/bc-csharp/issues/447

**Comment by jstedfast** [comment]
I think there are 2 possible solutions. Either I bring back net6.0 (which I'd hate to do because then I'm forced to support a framework that Microsoft no longer supports) or we can try to get BouncyCastle to add the netstandard2.1 target (and maybe the net8.0 target while we're at it).

**Comment by jstedfast** [comment]
Or a third option is you update your app to target net8.0 😄

**Comment by jvorwerk** [comment]
Thank you very much for your quick response. We have updated our app to target net8.0 and this has solved the problem :-)
