### ISSUE TITLE
Exception while importing certificate to postgres DB

### ISSUE THREAD

**Issue by OlehKhitrin** [jstedfast/MimeKit#286]
I'm trying to use postgres for certificates posession. When I import certificate, I receive a "System.InvalidOperationException".
Message: "@ALGORITHMS' must have its value set"
StackTrace:   
   at Npgsql.NpgsqlParameter.ResolveHandler(TypeHandlerRegistry registry)
   at Npgsql.NpgsqlParameter.Bind(TypeHandlerRegistry registry)
   at Npgsql.NpgsqlCommand.ValidateParameters()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at MimeKit.Cryptography.X509CertificateDatabase.Add(X509CertificateRecord record)
   at MimeKit.Cryptography.DefaultSecureMimeContext.Import(X509Certificate certificate)
Does anybody know how to fix it?

**Comment by jstedfast** [comment]
MimeKit created the table to allow null values in the ALGORITHMS column, but apparently Postgres is a bit stricter than the other SQL-backends which work fine.

Could you grab the latest source code, compile it, and check that it works for you now?

If it does, I'll make a new nuget release this weekend (or as soon as I hear back from you that this fixes things).

**Comment by OlehKhitrin** [comment]
Hello,
it didn't help. After your fix I started to receive an error "Parameter
'@PRIVATEKEY' must have its value set".
I substituted string №411 in SqlCertificateDatabase with
command.AddParameterWithValue(variable, value ?? DBNull.Value);
It worked for me.

2017-03-09 15:40 GMT+02:00 Jeffrey Stedfast <notifications@github.com>:

**Comment by jstedfast** [comment]
Try that.

**Comment by OlehKhitrin** [comment]
Recent changes work good. Could you roll out a new version in nuget?

2017-03-09 19:54 GMT+02:00 Jeffrey Stedfast <notifications@github.com>:

**Comment by jstedfast** [comment]
I'll push out a new release this weekend. Thanks for verifying the fix!
