### ISSUE TITLE
Header Parsing Issue

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#450]
When loading an email stream a header cannot be parsed causing the load to throw and error.

**To Reproduce**
1. I have an email with this header:
IronPort-PHdr: =?us-ascii?q?9a23=3AlmtJyhBzY918l/2JwwvTUyQJP3N1i/DPJgcQr6Af?=
 =?us-ascii?q?oPdwSPXypcbcNUDSrc9gkEXOFd2CrakV26yO6+jJYi8p2d65qncMcZhBBVcuqP?=
 =?us-ascii?q?49uEgeOvODElDxN/XwbiY3T4xoXV5h+GynYwAOQJ6tL1LdrWev4jEMBx7xKRR6?=
 =?us-ascii?q?JvjvGo7Vks+7y/2+94fdbghMhzexe69+IAmrpgjNq8cahpdvJLwswRXTuHtIfO?=
 =?us-ascii?q?pWxWJsJV2Nmhv3+9m98p1+/SlOovwt78FPX7n0cKQ+VrxYES8pM3sp683xtBnM?=
 =?us-ascii?q?VhWA630BWWgLiBVIAgzF7BbnXpfttybxq+Rw1DWGMcDwULs5Qiqp4bt1RxD0iS?=
 =?us-ascii?q?cHLz85/3/Risxsl6JQvRatqwViz4LIfI2ZMfxzdb7fc9wHX2pMRsZfWTJcDIOg?=
 =?us-ascii?q?YYUBDOQBMuREoIbyvFYBtweyCA22Ce/z1jNFhnn71rA63eQ7FgHG2RQtEswJsH?=
 =?us-ascii?q?TTtNX6Kr0SWv23wqbWyTXMcfVW0ir65oPVdR0vo++DXbZufsrX00UiCQTFjlKI?=
 =?us-ascii?q?qYP7JTOYzfwNsmmH4Op9TuKvkGknqwdqojS12sgsjYzJi5sTx1vZ9it52J44Kc?=
 =?us-ascii?q?C8RUN7e9KoDpRduiGAO4doTM4uX3tktDs7x7EYoZK3YjUGxZY9yxLCZfGKc5KE?=
 =?us-ascii?q?7x3+WOqLPDt1hW9pdKqxhxms8kWs1ujxW8y23VtOqidJj9zBuWwQ2BHS5cWKT+?=
 =?us-ascii?q?dy8lqu1DmR0g3f9+VJLEMwmKfdNpUv2KQ/loAJvkTGBiL2mFv5jKuRdkg8/+in?=
 =?us-ascii?q?8eXnYrH7qpOGLIB7lAT+Mrg0lcGxG+g4NxYBX3OA+eum273s40n5T69Rgf0tiK?=
 =?us-ascii?q?XWrJfaJcEDqq64BQ9azJoj5g6iAzqi0NkUh2cLIV1FdR6dkYTkNU3CLOrlAfq+?=
 =?us-ascii?q?nVigiDJryOrHPr3lDJXNNH/DkLL5cLh/9UFczBQ8zdZF659KDbEBJ+rzVVHrtN?=
 =?us-ascii?q?HDFh84MhC7w/v8CNVm0YMeX3mPDrWFP6PVtF+E/vgvLPWUZI8JpDb9LOAo6OXw?=
 =?us-ascii?q?gn42g1MdZqyp3ZoLaHC4BflpOEKZYX3wgtcaDGsGpA0+TOrviF2DTTFTfXGyX7?=
 =?us-ascii?q?k75jE1FIKqF5vMRoeogLaZxie0AoVWZnxaClCLCXrnbZiLVO0JaC6IOcBujDgE?=
 =?us-ascii?q?VaOhS4A72xCjrxT1y71gLurI4S0UqIjv1N9z5+3WlBE96SZ0D8OG02GKQWF0gn?=
 =?us-ascii?q?kESCMx3KB68gRBzQKp3LgwuPlZCdwbs9lEQkEBMJ/Az8RwDNfuQUTKeZGUSwD1?=
 =?us-ascii?q?bM+hBGQaSdUpzsVGQ0t5FtPqq1iX/yeuDrlTvLuMHJEu2rrO1GXqPMF70DDN06?=
 =?us-ascii?q?x33ApueddGKWDz3v03zAPUHYOc1hzBz6s=3D?=

2. When using the *MimeKit.MimeMessage.Load(stream);* call the following error is thrown:
System.FormatException was unhandled
  HResult=-2146233033
  Message=Failed to parse message headers.
  Source=MimeKit
  StackTrace:
       at MimeKit.MimeParser.ParseMessage(Byte* inbuf, CancellationToken cancellationToken)
       at MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
       at MimeKit.MimeMessage.Load(ParserOptions options, Stream stream, Boolean persistent, CancellationToken cancellationToken)
       at MimeKit.MimeMessage.Load(Stream stream, CancellationToken cancellationToken)
       at PRGX.MT.EML.MessageReceived..ctor(Stream stream) in C:\Users\lcarpe01\Documents\Visual Studio 2015\Projects\MailTraxHD\PRGX.MT.EML\MessageReceived.cs:line 65
       at PRGX.MT.UI.EmailViewer.EMLViewer.ReadEML(String EMailGUID, StreamReader emailStream) in C:\Users\lcarpe01\Documents\Visual Studio 2015\Projects\MailTraxHD\PRGX.MT.UI.EmailViewer\EMLViewer.vb:line 345
       at PRGX.MT.Utilities.EmailViewer.FormEmailViewer.FormEmailViewer_Shown(Object sender, EventArgs e) in C:\Users\lcarpe01\Documents\Visual Studio 2015\Projects\MailTraxHD\PRGX.MT.Utilities.EmailViewer\FormEmailViewer.cs:line 50
       at System.Windows.Forms.Form.OnShown(EventArgs e)
       at System.Windows.Forms.Form.CallShownEvent()
       at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
       at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
       at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.ContainerControl.WndProc(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at Telerik.WinControls.UI.RadFormControlBase.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at PRGX.MT.Utilities.EmailViewer.Program.Main() in C:\Users\lcarpe01\Documents\Visual Studio 2015\Projects\MailTraxHD\PRGX.MT.Utilities.EmailViewer\Program.cs:line 25
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

**Expected behavior**
Outlook can load the message, I would still like to be able to load the message, however this header looks like a mess.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - MimeKit 2.0.3

**Comment by LeeBear35** [comment]
I just updated to the 2.0.7 release and the header parses okay.
