### ISSUE TITLE
Failed to parse Authentication Results where smtp.mailfrom contains an "="

### ISSUE THREAD

**Issue by The-Nutty** [jstedfast/MimeKit#590]
**Describe the bug**
`AuthenticationResults.Parse` Throws an error when the smtp.mailfrom address contains an "="

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: Net core 3.1
 - MimeKit Version: 2.9.1

**To Reproduce**
Run the follwing code `            var ar = AuthenticationResults.Parse(Encoding.ASCII.GetBytes(@"i=1;	relay.mailrelay.com;	dkim=pass header.d=domaina.com header.s=sfdc header.b=abcefg;	dmarc=pass (policy=quarantine) header.from=domaina.com;	spf=pass (relay.mailrelay.com: domain of support=domaina.com__0-1q6woix34obtbu@823lwd90ky2ahf.mail_sender.com designates 1.1.1.1 as permitted sender) smtp.mailfrom=support=domaina.com__0-1q6woix34obtbu@823lwd90ky2ahf.mail_sender.com"));`

Currently it throws with the following Exception:
```
MimeKit.ParseException: Invalid propspec token at offset 315
   at MimeKit.Cryptography.AuthenticationResults.TryParseMethods(Byte[] text, Int32& index, Int32 endIndex, Boolean throwOnError, AuthenticationResults authres)
   at MimeKit.Cryptography.AuthenticationResults.TryParse(Byte[] text, Int32& index, Int32 endIndex, Boolean throwOnError, AuthenticationResults& authres)
   at MimeKit.Cryptography.AuthenticationResults.Parse(Byte[] buffer)
   at Testing.Program.Main(String[] args) in D:\other code\C#\Testing\Testing\Program.cs:line 388
   at Testing.Program.<Main>(String[] args)
```

**Expected behavior**
I would expect the string to parse correctly.

**Comment by jstedfast** [comment]
`=` is a `tspecial` character which is technically not allowed :-\

**Comment by The-Nutty** [comment]
Yeah i did think it was very odd, thanks for the quick response.

**Comment by jstedfast** [comment]
No problem. Let me know if my work-around doesn't work for you. I made the code a lot more liberal in what it accepts.
