### ISSUE TITLE
SSL Gsuite - Error occurred during a cryptographic operation

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MimeKit#689]
**Describe the bug**
I use you library to relay email to Gsuite. Everything worked fine until friday when we got this error and we could not relay emails to Gsuite anymore. The Gsuite conf did not changed nor did the code of our software. We talked opended a ticket with gsuite and they told us that nothing has changed. 

```
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.
 ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.MapVerifyErrorToChainStatus(X509VerifyStatusCode code)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.AddElementStatus(X509VerifyStatusCode errorCode, List`1 elementStatus, List`1 overallStatus)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.AddElementStatus(List`1 errorCodes, List`1 elementStatus, List`1 overallStatus)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.BuildChain(X509Certificate2 leaf, HashSet`1 candidates, HashSet`1 systemTrusted, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag,
 DateTime verificationTime, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag
```

**Platform (please complete the following information):**
 - OS: Linux
 - .NET Runtime: NET Core 2.2
 - MimeKit Version: 2.13

**Additional context**
We tried to apply the solutions you give us on this link https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException but we had no luck.

Code:

```
smtp.Connect("smtp-relay.gmail.com", 587, SecureSocketOptions.Auto); //we tried with StartSSL and the other options
message.Prepare(EncodingConstraint.SevenBit);
await smtp.SendAsync(message, sender, recipients);
smtp.Disconnect(true);
smtp.Dispose();

```
Any idea of what could be the problem?
Thank you very much!

**Comment by jstedfast** [comment]
That seems to be caused by some sort of cryptography error in SslStream which is not part of MailKit (MailKit only uses it).

I would recommend filing a bug report against the Microsoft .NET class libraries.
