### ISSUE TITLE
Emails with single charcter as the From Name exception when getting From address

### ISSUE THREAD

**Issue by julietreid** [jstedfast/MimeKit#846]
**Describe the bug**
An email with a single character From Name throws exception when trying to read the From address

**Platform:**
 - OS: Windows
 - .NET Runtime: .NET 6.0
 - .NET Framework: .NET 6.0
 - MimeKit Version: 3.4.1

**To Reproduce**
1. Load the attached email
2. Attempt to read the From address
3. ArgumentOutOfRangeException

**Expected behavior**
Can get the name/address from the From field

**Code Snippets**
```csharp
async Task Main()
{
	var message = await MimeMessage.LoadAsync(@"test1char.txt");
	Console.WriteLine(message.From.Mailboxes.FirstOrDefault()?.Address);
}
```

**Additional context**
```
Specified argument was out of the range of valid values. (Parameter 'minimumLength')
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at MimeKit.Utils.MimeUtils.Unquote(Byte[] text, Int32 startIndex, Int32 length, Boolean convertTabsToSpaces) in D:\src\MimeKit\MimeKit\Utils\MimeUtils.cs:line 584
   at MimeKit.InternetAddress.TryParse(AddressParserFlags flags, ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, InternetAddress& address) in D:\src\MimeKit\MimeKit\InternetAddress.cs:line 856
   at MimeKit.InternetAddressList.TryParse(AddressParserFlags flags, ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Boolean isGroup, Int32 groupDepth, List`1& addresses) in D:\src\MimeKit\MimeKit\InternetAddressList.cs:line 592
   at MimeKit.MimeMessage.AddAddresses(Header header, InternetAddressList list) in D:\src\MimeKit\MimeKit\MimeMessage.cs:line 2475
   at MimeKit.MimeMessage.GetLazyLoadedAddresses(HeaderId id, LazyLoadedFields bit) in D:\src\MimeKit\MimeKit\MimeMessage.cs:line 571
   at MimeKit.MimeMessage.get_From() in D:\src\MimeKit\MimeKit\MimeMessage.cs:line 596
   at UserQuery.Main(), line 4
```

File that crashes
[test1char.txt](https://github.com/jstedfast/MimeKit/files/9822718/test1char.txt)

**Comment by jstedfast** [comment]
This is the same bug as issue #847 that I just fixed
