### ISSUE TITLE
Concurrency/race condition using BodyBuilder.AddAttachment() in parallel

### ISSUE THREAD

**Issue by dylanbeattie** [jstedfast/MimeKit#874]
I have an application that uses a queue based on System.Threading.Channels to queue and send hundreds of email messages via queued background tasks - multiple threads running within a single application process. Under heavy load, I'm seeing two intermittent errors from MimeKit. 

I've been able to reproduce the error using `Parallel.ForEach` - see the repro cases below.

One is an `ArgumentOutOfRangeException` in `HeaderList.Replace(Header header)`:

```
System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at MimeKit.HeaderList.Replace(Header header) in D:\MimeKit\MimeKit\HeaderList.cs:line 1010
   at MimeKit.MimeEntity.SetHeader(String name, Byte[] rawValue) in D:\MimeKit\MimeKit\MimeEntity.cs:line 1201
   at MimeKit.MimeEntity.SerializeContentType() in D:\MimeKit\MimeKit\MimeEntity.cs:line 1220
   at MimeKit.MimeEntity.ContentTypeChanged(Object sender, EventArgs e) in D:\MimeKit\MimeKit\MimeEntity.cs:line 1230
   at MimeKit.ContentType.OnChanged() in D:\MimeKit\MimeKit\ContentType.cs:line 402
   at MimeKit.ContentType.OnParametersChanged(Object sender, EventArgs e) in D:\MimeKit\MimeKit\ContentType.cs:line 397
   at MimeKit.ParameterList.OnChanged() in D:\MimeKit\MimeKit\ParameterList.cs:line 668
   at MimeKit.ParameterList.OnParamChanged(Object sender, EventArgs args) in D:\MimeKit\MimeKit\ParameterList.cs:line 663
   at MimeKit.Parameter.OnChanged() in D:\MimeKit\MimeKit\Parameter.cs:line 735
   at MimeKit.Parameter.set_Value(String value) in D:\MimeKit\MimeKit\Parameter.cs:line 284
   at MimeKit.ParameterList.set_Item(String name, String value) in D:\MimeKit\MimeKit\ParameterList.cs:line 265
   at MimeKit.ContentType.set_Name(String value) in D:\MimeKit\MimeKit\ContentType.cs:line 252
   at MimeKit.AttachmentCollection.CreateAttachment(ContentType contentType, String path, Stream stream, CancellationToken cancellationToken) in D:\MimeKit\MimeKit\AttachmentCollection.cs:line 257
   at MimeKit.AttachmentCollection.Add(String fileName, Byte[] data, ContentType contentType)
D:\MimeKit\MimeKit\AttachmentCollection.cs:line 337
   at UnitTests.AssortedTests.<>c__DisplayClass12_0.<TestAddDoesNotCauseRaceConditions>b__1(Guid guid) in 
```

The other is an `ArgumentException` calling `MimeKit.ParameterList.Add(Parameter param)`:

```
System.ArgumentException : A parameter of that name already exists. (Parameter 'param')
   at MimeKit.ParameterList.Add(Parameter param) in D:\MimeKit\MimeKit\ParameterList.cs:line 365
   at MimeKit.ParameterList.Add(String name, String value) in D:\MimeKit\MimeKit\ParameterList.cs:line 79
   at MimeKit.ParameterList.set_Item(String name, String value) in D:\MimeKit\MimeKit\ParameterList.cs:line 266
   at MimeKit.ContentType.set_Name(String value) in D:\MimeKit\MimeKit\ContentType.cs:line 252
   at MimeKit.AttachmentCollection.CreateAttachment(ContentType contentType, String path, Stream stream, CancellationToken cancellationToken) in D:\MimeKit\MimeKit\AttachmentCollection.cs:line 257
   at MimeKit.AttachmentCollection.Add(String fileName, Byte[] data, ContentType contentType) in D:\MimeKit\MimeKit\AttachmentCollection.cs:line 337
   at UnitTests.AssortedTests.<>c__DisplayClass12_0.<TestAddDoesNotCauseRaceConditions>b__1(Guid guid) in D:\MimeKit\UnitTests\AssortedTests.cs:line 286```
```

**Platform**

Verified on Windows 10 Pro (x64, .NET 6), and on Linux (Azure AppService using .NET 6)

**MimeKit Version**: 3.4.3 (from NuGet, and verified building from the 3.4.3 tagged source)

**To Reproduce**

Running this code with `HOW_MANY_CASES = 200` has about a 99% chance of reproducing the error:

```csharp
[Test]
public void TestAddDoesNotCauseRaceConditions ()
{
  const int HOW_MANY_CASES = 200;
  var contentType = new ContentType ("application", "pdf");
  var cases = Enumerable.Range (0, HOW_MANY_CASES).Select (i => Guid.NewGuid ());
  var from = new MailboxAddress ("test", "test@example.com");
  var messages = new List<MimeMessage> ();
  Parallel.ForEach (cases, guid => {
    var mm = new MimeMessage ();
    mm.Subject = guid.ToString ();
    mm.From.Add (from);
    mm.To.Add (new MailboxAddress (guid.ToString (), $"{guid}@example.com"));
    var bb = new BodyBuilder { HtmlBody = String.Empty, TextBody = String.Empty };
    var filename = $"{guid}.pdf";
    var bytes = guid.ToByteArray ();
    bb.Attachments.Add (filename, bytes, contentType);
    mm.Body = bb.ToMessageBody ();
    messages.Add (mm);
  });
  Assert.AreEqual (HOW_MANY_CASES, messages.Count);
}
```

I also created a test that will run the same tests 100 times, with varying degrees of parallelism:

```csharp
[Test]
public void TestAddDoesNotCauseRaceConditions ()
{
  const int RUNS = 100;
  var results = new Dictionary<int, int> ();
  foreach (var caseCount in new[] { 1, 2, 5, 10, 20, 50, 100, 200, 500, 1000 }) {
    var passes = 0;
    for (var i = 0; i < RUNS; i++) {
      var contentType = new ContentType ("application", "pdf");
      var cases = Enumerable.Range (0, caseCount).Select (i => Guid.NewGuid ());
      var from = new MailboxAddress ("test", "test@example.com");
      var messages = new List<MimeMessage> ();
      try {
        Parallel.ForEach (cases, guid => {
          var mm = new MimeMessage ();
          mm.Subject = guid.ToString ();
          mm.From.Add (from);
          mm.To.Add (new MailboxAddress (guid.ToString (), $"{guid}@example.com"));
          var bb = new BodyBuilder { HtmlBody = String.Empty, TextBody = String.Empty };
          var filename = $"{guid}.pdf";
          var bytes = guid.ToByteArray ();
          bb.Attachments.Add (filename, bytes, contentType);
          mm.Body = bb.ToMessageBody ();
          messages.Add (mm);
        });
        passes++;
      } catch (Exception ex) {
        Console.WriteLine (ex.Message);
        Console.WriteLine (ex.StackTrace);
      }
    }
    results.Add (caseCount, passes);
  }
  foreach (var result in results) {
    Console.WriteLine ("|" + result.Key + "|" + (RUNS - result.Value) + "|");
  }
}
```

Here's the results:

| Parallelism| Test failures (in 100 runs) |
| ----------- | --------------------------- |
| 1 | 0 |
| 2 | 3 |
| 5 | 7 |
| 10 | 15 |
| 20 | 17 |
| 50 | 44 |
| 100 | 72 |
| 200 | 99 |
| 500 | 100 |
| 1000 | 100 |

My first hunch on this was that is was due to something like accessing a static dictionary without using a lock - but I've spent a few hours digging through the code and I'm at a complete loss as to where the concurrency issues are coming from. I'm now wondering if it's something to do with event handlers being attached and invoked in an unpredictable order?

I'll continue to investigate and hopefully have a PR in a few days, but wanted to flag up the issue now in case anybody has any bright ideas or can point me in the right direction...

**Comment by dylanbeattie** [comment]
OK, this is interesting. If I declare a new `ContentType` instance for every message, no more concurrency problems. So I'm guessing that passing a `ContentType` instance into `Attachments.Add` actually modifies the instance that's passed in, and so `ContentType` can't safely be reused between threads - even though it looks like all it's doing is specifying a MIME type?

```
[Test]
public void TestAddDoesNotCauseRaceConditions ()
{
	const int howManyCases = 10000;
	var cases = Enumerable.Range (0, howManyCases).Select (i => Guid.NewGuid ());
	var messages = new List<MimeMessage> ();
	var from = new MailboxAddress ("test", "test@example.com");
	Parallel.ForEach (cases, guid => {
		var mm = new MimeMessage ();
		mm.Subject = guid.ToString ();
		mm.From.Add (from);
		var contentType = new ContentType ("application", "pdf");
		mm.To.Add (new MailboxAddress (guid.ToString (), $"{guid}@example.com"));
		var bb = new BodyBuilder { HtmlBody = String.Empty, TextBody = String.Empty };
		var filename = $"{guid}.pdf";
		var bytes = guid.ToByteArray ();
		bb.Attachments.Add (filename, bytes, contentType);
		mm.Body = bb.ToMessageBody ();
		messages.Add (mm);
	});
	Assert.AreEqual (howManyCases, messages.Count);
}
```

**Comment by jstedfast** [comment]
The ContentType is set as the attachment's ContentType property and will then have the file name set on it by the AttachmentCollection.Add() method.

So yea, that's the issue.

Maybe it should be cloned by the Add() method, I'm not sure what the standard practice is.

**Comment by jstedfast** [comment]
Fwiw, I'm pretty sure you could use an Add() method that did not take a ContentType parameter and it would correctly identify it to be application/pdf based on the file name.

**Comment by dylanbeattie** [comment]
Yep, omitting the `ContentType` completely works just fine - thanks.

Cloning the ContentType when it's added would certainly have saved me a lot of confusion - having spent way more time working on web apps than I have on email, I see "ContentType" and assume it's just a wrapper around a MIME type string, like it would be if it was an HTTP header. It didn't even occur to me that it might be something mutable that could lead to concurrency issues.

MimeKit is a fantastic library, by the way. Thank you for all the hard work. ❤

**Comment by jstedfast** [comment]
I've added a ContentType.Clone() method, but I haven't decided whether I should modify AttachmentCollection.Add() methods to clone the ContentType parameters, mostly because I'm not sure if that will break anyone's usage.

For example, someone out there could be doing:

```csharp
var contentType = new ContentType(...);
bodyBuilder.Attachments.Add(contentType, ...);
contentType.Name = "foobar.txt";
```

If I clone the contentType, then this would no longer set the Name parameter on the attachment.
