### ISSUE TITLE
Oplock exception on MimeMessage.WriteToAsync

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MimeKit#906]
@jstedfast I experienced a freak issue, which I don't think it actaully would fall on your plate. Nevertheless I figured I reported the issue in case you had any idea what might be going on.

- I was composing a mail with 2 PDF attachements which had been added by drag&drop. Basically, drop&drop reported the filenames of the attachments which then made me add them as `MimeParts `to a `MultiPart `body
```
new MimePart
{
	Content			= new MimeContent(await storageFile.OpenStreamForReadAsync(), ContentEncoding.Default),
	ContentDisposition	= new ContentDisposition(ContentDisposition.Attachment),
	ContentTransferEncoding	= ContentEncoding.Base64,
	FileName			= Path.GetFileName(storageFile.Path),
}
```
- on saving the whole `MimeMessage` in my local repo (before actually sending the mail!) I got this exception
```
2023-03-21 12:15:57:403 System.Runtime.InteropServices.COMException (0x80070323): The handle with which this oplock was associated has been closed.  The oplock is now broken. (0x80070323)
   at Windows.Storage.Streams.WinRtToNetFxStreamAdapter.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Windows.Storage.Streams.WinRtToNetFxStreamAdapter.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(Memory`1 buffer, CancellationToken cancellationToken, Int32 bytesAlreadySatisfied, Task semaphoreLockTask)
   at MimeKit.MimeContent.WriteToAsync(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MimeContent.DecodeToAsync(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MimePart.WriteToAsync(FormatOptions options, Stream stream, Boolean contentOnly, CancellationToken cancellationToken)
   at MimeKit.Multipart.WriteToAsync(FormatOptions options, Stream stream, Boolean contentOnly, CancellationToken cancellationToken)
   at MimeKit.MimeMessage.WriteToAsync(FormatOptions options, Stream stream, Boolean headersOnly, CancellationToken cancellationToken)
   at Unusual.Mail.Mail.SaveAsync(DbConnection connection)
```

I'm pretty sure I have no concurrent access to the attachment files in my code.

Would you have idea whayt might have caused the freak (=non reproducible) issue? 
Thanks in advance

**Comment by DierkDroth** [comment]
Thanks @jstedfast for your speedy reply. I'll give that a try...
