### ISSUE TITLE
Intermittent Cannot access a disposed object exception in ChainedStream

### ISSUE THREAD

**Issue by AndrewCravenGMSL** [jstedfast/MimeKit#916]
**Describe the bug**
We are seeing a Cannot access a disposed object exception in ChainedStream in our integration tests that test an API endpoint that uses `MimeEntity.LoadAsync`.

We first encountered this in CI GitHub Actions, but it wasn't occurring on our development machines. We were only able to reproduce by restricting the Docker resources using the `.wslconfig` as snippet below (see [this link](https://learn.microsoft.com/en-us/windows/wsl/wsl-config) for more information).

We have removed all unrelated code from our service and have create a minimum repro in PR https://github.com/jstedfast/MimeKit/pull/915.

**Platform (please complete the following information):**
 - OS: Linux in Docker/WSL2 on Windows (also in CI on GitHub Actions workflow `ubuntu-latest`)
 - .NET Runtime: .NET 6
 - .NET Framework: .NET 6
 - MimeKit Version: 4.0.0

**To Reproduce**
1. Install Docker
2. Add/update `.wslconfig` as snippet below and restart machine
3. Go to 'failure-repro' folder in https://github.com/jstedfast/MimeKit/pull/915
4. Run 'test-webapi.ps1'
5. See intermittent errors in `Failing_mime_parsing` test which calls `/mime/fails` and successes in `Successful_mime_parsing` which calls `mime/succeeds`

**Expected behavior**
We don't expect any of these tests to fail.

**Code Snippets**

`.wslconfig`
```
[wsl2]
#GitHub hosted runner spec
memory=7GB
processors=2
```

**Typical exception stack**
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ChainedStream'.
   at MimeKit.IO.ChainedStream.CheckDisposed()
   at MimeKit.IO.ChainedStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ReadAheadAsync(Int32 atleast, Int32 save, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ScanContentAsync(Stream content, Boolean trimNewLine, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ConstructMimePartAsync(MimePart part, MimeEntityEndEventArgs args, CancellationToken cancellationToken)
   at MimeKit.MimeParser.MultipartScanSubpartsAsync(Multipart multipart, Int32 depth, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ConstructMultipartAsync(Multipart multipart, MimeEntityEndEventArgs args, Int32 depth, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseEntityAsync(CancellationToken cancellationToken)
   at Gmsl.WebApi.EntryController.ParseFailsAsync() in /build/Gmsl.WebApi/EntryController.cs:line 20
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jstedfast** [comment]
Thanks. MimeEntity.LoadAsync() was returning an async task without awaiting it, allowing the ChainedStream to be disposed when the method went out of scope.
